$background = rgb({"dark": Map({"color": Ident("#11140e")}), "default": Map({"color": Ident("#11140e")}), "light": Map({"color": Ident("#f8faf0")})})
$foreground = rgb({"dark": Map({"color": Ident("#e1e4d9")}), "default": Map({"color": Ident("#e1e4d9")}), "light": Map({"color": Ident("#191d16")})})

$primary    = rgb({"dark": Map({"color": Ident("#abd28f")}), "default": Map({"color": Ident("#abd28f")}), "light": Map({"color": Ident("#466730")})})
$secondary  = rgb({"dark": Map({"color": Ident("#bdcbaf")}), "default": Map({"color": Ident("#bdcbaf")}), "light": Map({"color": Ident("#56624b")})})
$accent     = rgb({"dark": Map({"color": Ident("#a0cfcf")}), "default": Map({"color": Ident("#a0cfcf")}), "light": Map({"color": Ident("#386666")})})

