background {"dark": Map({"color": Ident("#11140e")}), "default": Map({"color": Ident("#11140e")}), "light": Map({"color": Ident("#f8faf0")})}
foreground {"dark": Map({"color": Ident("#e1e4d9")}), "default": Map({"color": Ident("#e1e4d9")}), "light": Map({"color": Ident("#191d16")})}

color0  {"dark": Map({"color": Ident("#11140e")}), "default": Map({"color": Ident("#11140e")}), "light": Map({"color": Ident("#f8faf0")})}
color1  {"dark": Map({"color": Ident("#ffb4ab")}), "default": Map({"color": Ident("#ffb4ab")}), "light": Map({"color": Ident("#ba1a1a")})}
color2  {"dark": Map({"color": Ident("#abd28f")}), "default": Map({"color": Ident("#abd28f")}), "light": Map({"color": Ident("#466730")})}
color3  {"dark": Map({"color": Ident("#bdcbaf")}), "default": Map({"color": Ident("#bdcbaf")}), "light": Map({"color": Ident("#56624b")})}
color4  {"dark": Map({"color": Ident("#a0cfcf")}), "default": Map({"color": Ident("#a0cfcf")}), "light": Map({"color": Ident("#386666")})}

